// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://soboqtnidzekkinomawf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvYm9xdG5pZHpla2tpbm9tYXdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxOTU2NDYsImV4cCI6MjA3MTc3MTY0Nn0.7rrGn4CgBMNAUchYJMLMxTmhoQ0EuBipr7bk6e9Z5yA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});